### PR TITLE
Wrap DropInRequest in Parcelable Bundle

### LINKED ISSUE #191: Class not found when unmarshalling: com.braintreepayments.api.dropin.DropInRequest
### General information

* SDK/Library version: 4.6.0
* Environment: Sandbox
* Android Version and Device: Samsung Galaxy S10 with Android 10.0

### Issue description

I cannot even make work the "hello world" equivalent described on this page: https://developers.braintreepayments.com/start/hello-client/android/v3

I have added the following snippet:

```
        button.setOnClickListener {
            val dropInRequest = DropInRequest()
                    .clientToken("CLIENT_TOKEN_FROM_SERVER")
            startActivityForResult(dropInRequest.getIntent(this), REQUEST_CODE)
        }
```

And I get the following stack trace:

```
2020-08-18 10:32:09.777 5841-15936/? E/Parcel: Class not found when unmarshalling: com.braintreepayments.api.dropin.DropInRequest
    java.lang.ClassNotFoundException: com.braintreepayments.api.dropin.DropInRequest
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:454)
        at android.os.Parcel.readParcelableCreator(Parcel.java:3031)
        at android.os.Parcel.readParcelable(Parcel.java:2981)
        at android.os.Parcel.readValue(Parcel.java:2883)
        at android.os.Parcel.readArrayMapInternal(Parcel.java:3261)
        at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:292)
        at android.os.BaseBundle.unparcel(BaseBundle.java:236)
        at android.os.BaseBundle.getString(BaseBundle.java:1160)
        at android.content.Intent.getStringExtra(Intent.java:8548)
        at com.android.server.wm.ActivityStarter.startActivity(ActivityStarter.java:790)
        at com.android.server.wm.ActivityStarter.startActivity(ActivityStarter.java:694)
        at com.android.server.wm.ActivityStarter.startActivityMayWait(ActivityStarter.java:1925)
        at com.android.server.wm.ActivityStarter.execute(ActivityStarter.java:625)
        at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1707)
        at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1603)
        at com.android.server.wm.ActivityTaskManagerService.startActivity(ActivityTaskManagerService.java:1557)
        at android.app.IActivityTaskManager$Stub.onTransact(IActivityTaskManager.java:1690)
        at android.os.Binder.execTransactInternal(Binder.java:1021)
        at android.os.Binder.execTransact(Binder.java:994)
     Caused by: java.lang.ClassNotFoundException: com.braintreepayments.api.dropin.DropInRequest
        at java.lang.Class.classForName(Native Method) 
        at java.lang.Class.forName(Class.java:454) 
        at android.os.Parcel.readParcelableCreator(Parcel.java:3031) 
        at android.os.Parcel.readParcelable(Parcel.java:2981) 
        at android.os.Parcel.readValue(Parcel.java:2883) 
        at android.os.Parcel.readArrayMapInternal(Parcel.java:3261) 
        at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:292) 
        at android.os.BaseBundle.unparcel(BaseBundle.java:236) 
        at android.os.BaseBundle.getString(BaseBundle.java:1160) 
        at android.content.Intent.getStringExtra(Intent.java:8548) 
        at com.android.server.wm.ActivityStarter.startActivity(ActivityStarter.java:790) 
        at com.android.server.wm.ActivityStarter.startActivity(ActivityStarter.java:694) 
        at com.android.server.wm.ActivityStarter.startActivityMayWait(ActivityStarter.java:1925) 
        at com.android.server.wm.ActivityStarter.execute(ActivityStarter.java:625) 
        at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1707) 
        at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1603) 
        at com.android.server.wm.ActivityTaskManagerService.startActivity(ActivityTaskManagerService.java:1557) 
        at android.app.IActivityTaskManager$Stub.onTransact(IActivityTaskManager.java:1690) 
        at android.os.Binder.execTransactInternal(Binder.java:1021) 
        at android.os.Binder.execTransact(Binder.java:994) 
```

Someone got the same error detailed here: https://stackoverflow.com/questions/54221312/braintree-integration-error-class-not-found-com-braintreepayments-api-dropin but no answer.

Please note that I have even tried with a token generated from my server, but this should not be taken into account.

Moreover I cannot understand the situation which has been discussed in #57.

So if you guys have an idea of what's going on, any help would be very appreciated.

Thanks!

### LINKED ISSUE #228: NullPointerException
### General information

* SDK/Library version: 5.0.1
* Environment: Production
* Android Version and Device: Nexus 6, Android 7

### Issue description

I see this crash on Crashlytics
I create DropInRequest by this code:
DropInRequest dropInRequest = new DropInRequest().cardholderNameStatus(CardForm.FIELD_REQUIRED)
                    .disablePayPal()
                    .clientToken(stringControllerResponse);

And Intent to start DropInActivity i get from dropInRequest.
activity.startActivityForResult(dropInRequest.getIntent(activity), PaymentMethodService.REQUEST_BRAINTREE);

And therefore it is very strange that in DropInActivity dropInRequest is null, although the intent is taken from the same dropInRequest.

Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.driivz.mobile.android.evgo.driver/com.braintreepayments.api.dropin.DropInActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.braintreepayments.api.dropin.DropInRequest.g()' on a null object reference
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2665)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
       at android.app.ActivityThread.-wrap12(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6119)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
       at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)

Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.braintreepayments.api.dropin.DropInRequest.g()' on a null object reference
       at com.braintreepayments.api.dropin.BaseActivity.getBraintreeFragment(BaseActivity.java:50)
       at com.braintreepayments.api.dropin.DropInActivity.onCreate(DropInActivity.java:110)
       at android.app.Activity.performCreate(Activity.java:6679)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
       at android.app.ActivityThread.-wrap12(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6119)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
       at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)

### PR DESCRIPTION
**Pull request by sarahkoop**
### Summary of changes

 - Set explicit class loader for `DropInRequest` (fixes #191)
 - Wrap `DropInRequest` in Parcelable bundle (fixes #228)

 ### Checklist

 - [x] Added a changelog entry

- @sarahkoop

### CODE REVIEW

**Review by sshropshire — APPROVED** [review]
🌊

File: Drop-In/src/main/java/com/braintreepayments/api/DropInActivity.java [hunk 1]
```diff
@@ -148,6 +148,13 @@ void finishDropInWithError(Exception e) {
         finish();
     }
 
+    private DropInRequest getDropInRequest(Intent intent) {
+        Bundle bundle = intent.getParcelableExtra(DropInClient.EXTRA_CHECKOUT_REQUEST_BUNDLE);
```
Comment (sshropshire) [inline Drop-In/src/main/java/com/braintreepayments/api/DropInActivity.java:152]: This is awesome!

Comment (scannillo) [reply Drop-In/src/main/java/com/braintreepayments/api/DropInActivity.java:152]: My understanding of Intents was to pass data from one activity/fragment to another. I wonder if there's a potential case where the OS (or the merchant) clears Intents (or is doing something else with them), which in turn would break this flow.

Asking because if this isn't a common pattern - want to make there is no lost stability with this change.

Comment (sshropshire) [reply Drop-In/src/main/java/com/braintreepayments/api/DropInActivity.java:152]: Yeah since Android calls the constructors directly behind the scenes the Intent gives us an opportunity to inject launch args for Activities/Fragments. They are for the most part kept in memory from my understanding, but if an activity / fragment is restored that process should be protected by the OS.

Comment (sarahkoop) [reply Drop-In/src/main/java/com/braintreepayments/api/DropInActivity.java:152]: Also to clarify - we were always passing the DropInRequest to DropInActivity through an intent extra, now we are just adding one more layer by wrapping it in a bundle, so that we can explicitly load it with the DropInRequest class loader

**Review by scannillo — APPROVED** [review]
